# -*- coding: utf-8 -*-
"""TuproAL3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cx-zALIDMd2zklZq_wncE2k8c_GyVSkJ

# **KELOMPOK 3**

Didit Johar Maulana - 1301194021

Muhammad Fikry Saputra - 1301194300

Sri Utami - 1301194104
"""

import pandas as pd
import numpy as np
from math import sqrt
from math import *
from decimal import Decimal

!gdown --id 1aJ1Oo2kRcErnfdq84m9gAgfJZNEFWzi_

data = pd.read_excel('mobil.xls', index_col=None)
dataDrop = data.drop('Nama Mobil', axis=1)
print(dataDrop)

# Euclidean distance = √Σ(Ai-Bi)2
def euclideanDistance(d1, d2):
  return np.linalg.norm(d1-d2)

# Manhattan Distance = Σ|Ai – Bi|
def manhattanDistance(a, b):
    return sum(abs(val1-val2) for val1, val2 in zip(a,b))

# Minkowski distance = 
def p_root(value, root):     
    root_value = 1 / float(root)
    return round (Decimal(value) **
             Decimal(root_value), 3)
  
def minkowskiDistance(x, y, p_value): 
    return (p_root(sum(pow(abs(a-b), p_value)
            for a, b in zip(x, y)), p_value))

# Supremum distance
def supremDistance(a1, a2):
  return max(abs(b1 - b2) for b1, b2 in zip(a1,a2))

print('INPUT DATA')
print('----------')
ukuran = int(input('Ukuran : '))
kenyamanan = int(input('Kenyamanan : '))
irit = int(input('Irit : '))
kecepatan = int(input('Kecepatan : '))
harga = float(input('Harga : '))
listData = [ukuran, kenyamanan, irit, kecepatan, harga]
print(listData)
dataTest = np.array(listData)
dist = []
nameCar = []
dist2 = []
dist3 = []
dist4 = []
for i in range(len(dataDrop)):
  dataCar = np.array(dataDrop.iloc[i])
  dist.append(euclideanDistance(dataCar, dataTest))
  dist2.append(manhattanDistance(dataCar, dataTest))
  dist3.append(minkowskiDistance(dataCar, dataTest, 5))
  dist4.append(supremDistance(dataCar, dataTest))
  nameCar.append(data.iloc[i, 0])

# EUCLIDEAN DISTANCE
dataDrop['Euclidean Distance'] = dist
dataDrop['Name of Car'] = nameCar
dataResult = dataDrop.sort_values('Euclidean Distance').head(3)
print('------------------')
print('Euclidean Distance')
print('------------------')
print(dataResult)
print()
# MANHATTAN DISTANCE
dataDrop2 = data.drop('Nama Mobil', axis=1)
dataDrop2['Manhattan Distance'] = dist2
dataDrop2['Name of Car'] = nameCar
dataResult2 = dataDrop2.sort_values('Manhattan Distance').head(3)
print('------------------')
print('Manhattan Distance')
print('------------------')
print(dataResult2)
print()
# MINKOWSKI DISTANCE
dataDrop3 = data.drop('Nama Mobil', axis=1)
dataDrop3['Minkowski Distance'] = dist2
dataDrop3['Name of Car'] = nameCar
dataResult3 = dataDrop3.sort_values('Minkowski Distance').head(3)
print('------------------')
print('Minkowski Distance')
print('------------------')
print(dataResult3)
print()
# SUPREMUM DISTANCE
dataDrop4 = data.drop('Nama Mobil', axis=1)
dataDrop4['Supremum Distance'] = dist4
dataDrop4['Name of Car'] = nameCar
dataResult4 = dataDrop4.sort_values('Supremum Distance').head(3)
print('------------------')
print('Supremum Distance')
print('------------------')
print(dataResult4)

# CONCLUSION
dataResult.to_excel('rekomendasi.xls')