# -*- coding: utf-8 -*-
"""TuproStatistika.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/138jYXzRH9Gwx4Wxr6DBFnjivzU04VQsf

# TUGAS BESAR STATISTIKA KELOMPOK XXIII

Didit Johar Maulana - 1301194021
 
Gerin Aryo Prasetya - 1301194479
 
Romansa - 130119
 
Samuel - 1301194026
"""

system("gdown --id 1lgVgj6n1HSwgmTl9ReT8Jwj6Ym7jFG9j")

data = read.csv('BankChurners.csv')

head(data,20)

"""**Boxplot Distribution Customer Ages of Genders**"""

boxplot(data$Customer_Age~data$Gender, ylab='Age', xlab = 'Gender', main='Boxplot Distribution Customer Ages of Genders')

"""**Plot Distribution Credit Limit of Total Transaction**"""

plot(data$Credit_Limit,data$Total_Trans_Ct, xlab = 'Credit Limit', ylab = 'Total Transaction', main = 'Plot Distribution Credit Limit of Total Transaction', pch = 1, col = 'black' )
grid()

"""**Histogram of Customer Age**"""

hist(data$Customer_Age, xlab = 'Age', main = 'Histogram of Customer Age', border = 'white', col = c('violet','chocolate2'), freq = F, las = 1)
lines(density(data$Customer_Age), lwd = 4, col = "red")

"""**Correlation of Credit Limit and Total Transactions**"""

cor(data$Credit_Limit,data$Total_Trans_Ct, method = 'kendall')

cor.test(data$Customer_Age,data$Total_Trans_Ct, method = 'pearson')

"""**Barplot Card Category**"""

card <- factor(data$Card_Category)
card_data <- c(length(which('Blue' == card)),length(which('Gold' == card)),length(which('Platinum' == card)),length(which('Silver' == card)))
card_category <- c('Blue', 'Gold', 'Platinum', 'Silver')
barplot(card_data, names.arg = card_category, xlab = 'Card Category', col = 'violet', border = 'white', main = ' Card Category')

